# ==================== 公共配置 ====================
spring:
  application:
    name: campus-performance-statistics-system
  # 默认激活 local 环境
  profiles:
    active: local
  # Session 配置
  session:
    timeout: 2592000  # session 30 天过期
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# MyBatis Flex 公共配置
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true

# 服务公共配置
server:
  port: 6789
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000  # cookie 30 天过期

# springdoc-openapi 公共配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jgh.ghairouter.controller

# knife4j 公共配置
knife4j:
  enable: true
  setting:
    language: zh_cn
